# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camara_deputados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='camara_deputados.Deputy')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='camara_deputados.Speech')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.Speech')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='speechtheme',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='application.Theme'),
        ),
        migrations.AddField(
            model_name='speechsentence',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='application.Theme'),
        ),
        migrations.AddField(
            model_name='deputytheme',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputies', to='application.Theme'),
        ),
    ]
