# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camara_deputados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.Deputy')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='application.Deputy')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camara_deputados.Speech')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='application.Speech')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='speechindex',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='application.Theme'),
        ),
        migrations.AddField(
            model_name='speech',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, related_name='speeches', to='application.Theme'),
        ),
        migrations.AddField(
            model_name='deputy',
            name='theme',
            field=models.ManyToManyField(blank=True, null=True, related_name='deputies', to='application.Theme'),
        ),
    ]
