# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camara_deputados', '0001_initial'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_indexes', to='camara_deputados.Speech')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='application.Theme')),
            ],
        ),
    ]
